---
op_connect_host: "http://vault-oci.{{ tailscale_tailnet }}:{{ hostvars['vault'].opconnect.api.port }}"
op_connect_token: "{{ vault_op_connect_token }}"
op_connect_vault_id: "{{ vault_op_connect_vault_id }}"
