---
# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: "Dependency Review"
on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: read
    steps:
      # Use the gh API to check if the repository has dependency review enabled
      # We can check this at /repos/{owner}/{repo}/dependency-graph/compare/{baseref...headref}
      - name: Check if dependency review is enabled
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # The dependency review API will return a 403 if it is not enabled
          # The range is the base ref to the head ref of the PR
          status=$(gh api /repos/${{ github.repository }}/dependency-graph/compare/${{ github.base_ref }}...${{ github.sha }} -i 2>/dev/null | head -n 1 | awk '{ print $2 }')
          if [[ $status == "200" ]]; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      enabled: ${{ steps.check.outputs.enabled }}
  dependency-review:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: "Checkout Repository"
        if: needs.check.outputs.enabled == 'true'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: "Dependency Review"
        if: needs.check.outputs.enabled == 'true'
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4
