---
name: GitGuardian scan

on: [push, pull_request]

jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      # Configure 1Password Service Account
      - name: Configure 1Password Service Account
        uses: 1Password/load-secrets-action/configure@8d0d610af187e78a2772c2d18d627f4c52d3fbfb # v3
        id: configure-1password
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      # Fetch GITGUARDIAN_API_KEY from 1Password using load-secrets-action
      - name: Fetch Secrets from 1Password
        uses: 1Password/load-secrets-action@8d0d610af187e78a2772c2d18d627f4c52d3fbfb # v3
        id: fetch-secrets
        with:
          export-env: false
        env:
          GITGUARDIAN_API_KEY: op://Infrastructure/gitguardian/credentials/token
      - name: GitGuardian scan
        uses: GitGuardian/gg-shield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.after }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ steps.fetch-secrets.outputs.GITGUARDIAN_API_KEY}}
