---
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates a collection of open source static analysis tools
# with GitHub code scanning. For documentation, or to provide feedback, visit
# https://github.com/github/ossar-action
name: OSSAR

on:
  workflow_dispatch:
  # Uncomment the following lines to enable the workflow on push or pull request
  # push:
  #   branches:
  #     - "main"
  # pull_request:
  #   # The branches below must be a subset of the branches above
  #   branches:
  #     - "main"
  # schedule:
  #   - cron: "32 17 * * 5"

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: read
    steps:
      # Use the gh API to check if the repository has code scanning enabled
      # We can check this at /repos/{owner}/{repo}/code-scanning/alerts
      - name: Check if code scanning is enabled
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          status=$(gh api /repos/${{ github.repository }}/code-scanning/alerts -i 2>/dev/null | head -n 1 | awk '{ print $2 }')
          if [[ $status == "200" ]]; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      enabled: ${{ steps.check.outputs.enabled }}
  OSSAR-Scan:
    # OSSAR runs on windows-latest.
    # ubuntu-latest and macos-latest support coming soon
    needs: check
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        if: needs.check.outputs.enabled == 'true'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # Ensure a compatible version of dotnet is installed.
      # The [Microsoft Security Code Analysis CLI](https://aka.ms/mscadocs) is built with dotnet.
      - name: Install .NET
        if: needs.check.outputs.enabled == 'true'
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
        with:
          dotnet-version: "6.0"

      # Run open source static analysis tools
      - name: Run OSSAR
        if: needs.check.outputs.enabled == 'true'
        uses: github/ossar-action@v1
        id: ossar

      # Upload results to the Security tab
      - name: Upload OSSAR results
        if: needs.check.outputs.enabled == 'true'
        uses: github/codeql-action/upload-sarif@9e907b5e64f6b83e7804b09294d44122997950d6 # v4
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
