---
on:
  - pull_request
name: "Tartufo Scan"
jobs:
  tartufo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: godaddy/tartufo-action@3d4684c758fa9fdaf9b9cb044d0b9daa86606525 # tag=v3.2.1
        id: tartufo
        with:
          entropy: "true"
          regex: "true"
          scan-filenames: "true"
          include-submodule: "false"
