---
name: Template Sync
on:
  # cronjob trigger
  schedule:
    - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
    inputs:
      # optional: specify if workflows should be synced
      sync_workflows:
        description: "Sync workflows"
        required: false
        default: false
        type: boolean
jobs:
  repo-sync:
    # Only run on non-template repos
    if: github.repository != 'jon77p/template'
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      # Only run if sync workflows is true
      # Configure 1Password Service Account
      - name: Configure 1Password Service Account
        if: ${{ github.event.inputs.sync_workflows == 'true' }}
        id: configure-1password
        uses: 1Password/load-secrets-action/configure@d1a4e73495bde3551cf63f6c048588b8f734e21d # v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      # Fetch TEMPLATE_SYNC_APP_ID and TEMPLATE_SYNC_PRIVATE_KEY
      # from 1Password using load-secrets-action
      # Run only if configure-1password was successful
      - name: Fetch Secrets
        if: ${{ steps.configure-1password.outcome == 'success' }}
        uses: 1Password/load-secrets-action@d1a4e73495bde3551cf63f6c048588b8f734e21d # v1
        id: fetch-secrets
        with:
          export-env: false
        env:
          TEMPLATE_SYNC_APP_ID: op://Infrastructure/template-sync/app/app_id
          TEMPLATE_SYNC_PRIVATE_KEY: op://Infrastructure/template-sync/ssh/private_key
      # Run only if fetch-secrets was successful
      - name: Generate GitHub App Token
        # see: https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        if: ${{ steps.fetch-secrets.outcome == 'success' }}
        with:
          app_id: ${{ steps.fetch-secrets.outputs.TEMPLATE_SYNC_APP_ID }}
          private_key: ${{ steps.fetch-secrets.outputs.TEMPLATE_SYNC_PRIVATE_KEY }}
      - name: Set variables
        id: variables
        run: |
          # If github.event.inputs.sync_workflows is true, use the generated token
          if [ "${{ github.event.inputs.sync_workflows }}" = "true" ]; then
            echo "token=${{ steps.generate_token.outputs.token }}" >> $GITHUB_OUTPUTS
          else
            echo "token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUTS
          fi
      - name: Sync Template
        uses: AndreasAugustin/actions-template-sync@c6631d6e8aa5de34b29cd5b3a4c22327a159fc12 # v1.1.8
        with:
          github_token: ${{ steps.variables.outputs.token }}
          source_repo_path: jon77p/template
          upstream_branch: main
          pr_labels: template-sync
