---
name: Template Sync
on:
  # cronjob trigger
  schedule:
    - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
    inputs:
      # optional: specify if workflows should be synced
      sync_workflows:
        description: "Sync workflows"
        required: false
        default: false
        type: boolean
jobs:
  repo-sync:
    # Only run on non-template repos
    if: github.repository != 'jon77p/template'
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      # Only run if sync workflows is true
      - name: Generate GitHub App Token
        # see: https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@0d49dd721133f900ebd5e0dff2810704e8defbc6 # v1.8.2
        if: ${{ github.event.inputs.sync_workflows == 'true' }}
        with:
          app_id: ${{ secrets.TEMPLATE_SYNC_APP_ID }}
          private_key: ${{ secrets.TEMPLATE_SYNC_PRIVATE_KEY }}
      - name: Sync Template
        uses: AndreasAugustin/actions-template-sync@5584bd1e260ef04a0dce76e1a802e31befd6f5c4 # v1.1.2
        with:
          github_token: ${{ steps.generate_token.outputs.token if github.event.inputs.sync_workflows == 'true' else secrets.GITHUB_TOKEN }}
          source_repo_path: jon77p/template
          upstream_branch: main
          pr_labels: template-sync
